name: Update README

on:
  push:
    paths:
      - "hostings.yaml"
      - "hostings.schema.json"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install pyyaml jsonschema

      - name: Validate YAML Schema
        run: |
          python -c "
          import json, yaml, sys
          from jsonschema import validate, ValidationError
          try:
              with open('hostings.yaml') as yml_file, open('hostings.schema.json') as schema_file:
                  y=yaml.safe_load(yml_file)
                  s=json.load(schema_file)
                  validate(y, s)
                  print('✅ YAML is valid!')
          except ValidationError as e:
              sys.exit(f'❌ Validation error: {e.message}')
          "

      - name: Generate README.md
        run: python generate_markdown.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with latest hosting data" || echo "No changes to commit"
          git push
